### ISSUE TITLE
Neon - ethers.js library incompatibility

### ISSUE THREAD

**Issue by mich-master** [neonlabsorg/neon-support#28]
**Bug Description**
A script that deploys a contract using ethers.js library fails with the error.

**Steps to Reproduce**
Run the js ethers script
```
const factory = new UpgradeBeaconController__factory("UpgradeBeaconController);
const ubc = await factory.deploy(overrides);...
```
**Actual Behavior**

> factory.deploy
/Users/anna/code/nomad/monorepo/node_modules/@ethersproject/logger/src.ts/index.ts:261
        const error: any = new Error(message);
                           ^
Error: invalid hash (argument="value", value=undefined, code=INVALID_ARGUMENT, version=providers/5.6.1)
    at Logger.makeError (/Users/anna/code/nomad/monorepo/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/Users/anna/code/nomad/monorepo/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at Logger.throwArgumentError (/Users/anna/code/nomad/monorepo/node_modules/@ethersproject/logger/src.ts/index.ts:277:21)
    at Formatter.hex (/Users/anna/code/nomad/monorepo/node_modules/@ethersproject/providers/src.ts/formatter.ts:221:23)
    at Formatter.data (/Users/anna/code/nomad/monorepo/node_modules/@ethersproject/providers/src.ts/formatter.ts:225:29)
    at Function.Formatter.check (/Users/anna/code/nomad/monorepo/node_modules/@ethersproject/providers/src.ts/formatter.ts:449:42)
    at Formatter._block (/Users/anna/code/nomad/monorepo/node_modules/@ethersproject/providers/src.ts/formatter.ts:300:34)
    at Formatter.block (/Users/anna/code/nomad/monorepo/node_modules/@ethersproject/providers/src.ts/formatter.ts:306:21)
    at StaticJsonRpcProvider.<anonymous> (/Users/anna/code/nomad/monorepo/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1810:35)
    at step (/Users/anna/code/nomad/monorepo/node_modules/@ethersproject/providers/lib/base-provider.js:48:23) {
  reason: 'invalid hash',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: undefined,
  checkKey: 'extraData',
  checkValue: undefined
}

**Expected Behavior**
The contract is deployed successfully.

**Additional Context**
Found by Nomad team during contract deployment.

**Comment by gigimon** [comment]
I have found a problem. Ether.js failed on eth_getBlockByNumber request because it expect field: extraData but it doesn't exist in our response. This field must be a hash (ether.js check value).

```
2022-04-28 08:51:20.147 I neon_rpc_api_plugin.py:135 425 Proxy:NeonRpcApiPlugin {"req_id": "cf4ed39"} handle_request <<< 139718859659008 0x7f13862d7130 {"method":"eth_getBlockByNumber","params":["latest",false],"id":44,"jsonrpc":"2.0"}
...
2022-04-28 08:51:20.212 I neon_rpc_api_plugin.py:158 425 Proxy:NeonRpcApiPlugin {"req_id": "cf4ed39"} handle_request >>> 139718859659008 0x7f13862d7130 {"jsonrpc": "2.0", "id": 44, "result": {"gasUsed": "0x0", "hash": "0x7496996f2032f27b2b4a7c08e63dee3c2509403569f2c5d9321bc24e3f9b053a", "number": "0x5e6a1c", "parentHash": "0xb9b0034719227436a39153ba153be59fd9b202a1bc4a550a84282a9ccc6b5e3d", "timestamp": "0x626a5587", "transactions": [], "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "gasLimit": "0x6691b7"}} eth_getBlockByNumber resp_time_ms= 65.52720069885254
```

**Comment by gigimon** [comment]
fixed and deployed on devnet
